"""Render final Markdown output with YAML frontmatter."""

from datetime import datetime
from pathlib import Path

import yaml

from api.config import Config
from api.extractor import ExtractionResult
from api.quality import QualityFlag
from api.transcribe import TranscriptResult


def _format_duration(seconds: float) -> str:
    """Format seconds as 'Xm Ys' or 'Xh Ym Zs'."""
    h, remainder = divmod(int(seconds), 3600)
    m, s = divmod(remainder, 60)
    if h > 0:
        return f"{h}h {m:02d}m {s:02d}s"
    return f"{m}m {s:02d}s"


def _format_timestamp(seconds: float) -> str:
    """Format seconds as HH:MM:SS."""
    h, remainder = divmod(int(seconds), 3600)
    m, s = divmod(remainder, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def render(
    source_file: Path,
    duration: float,
    transcript: TranscriptResult,
    extraction: ExtractionResult | None,
    quality_flags: list[QualityFlag],
    config: Config,
) -> str:
    """Render complete Markdown output matching the requirements format."""
    now = datetime.now()
    lines: list[str] = []

    # --- YAML frontmatter ---
    frontmatter = {
        "meeting_date": now.strftime("%Y-%m-%d"),
        "meeting_time": now.strftime("%H:%M"),
        "duration": _format_duration(duration),
        "speakers": transcript.speaker_count,
        "audio_file": str(source_file.resolve()),
        "processing_date": now.isoformat(timespec="seconds"),
        "whisper_model": config.whisper_model,
        "llm_model": config.llm_model if extraction else "none",
    }
    if quality_flags:
        frontmatter["quality_flags"] = [
            {"type": f.type, "timestamp": f.timestamp, "description": f.description}
            for f in quality_flags
        ]

    lines.append("---")
    lines.append(yaml.dump(frontmatter, default_flow_style=False, sort_keys=False).strip())
    lines.append("---")
    lines.append("")

    # --- Header ---
    date_str = now.strftime("%B %d, %Y")
    lines.append(f"# Meeting Summary - {now.strftime('%Y-%m-%d')}")
    lines.append("")
    lines.append(f"**Duration**: {_format_duration(duration)}  ")
    lines.append(f"**Speakers**: {transcript.speaker_count}  ")
    lines.append(f"**Date**: {date_str} at {now.strftime('%H:%M')}")
    lines.append("")

    # --- Structured summary (if LLM extraction was done) ---
    if extraction:
        _render_topics(lines, extraction)
        _render_decisions(lines, extraction)
        _render_action_items(lines, extraction)
        _render_questions(lines, extraction)

    # --- Quality Notes ---
    if quality_flags:
        lines.append("---")
        lines.append("")
        lines.append("## Quality Notes")
        lines.append("")
        for flag in quality_flags:
            icon = "\u26a0\ufe0f" if flag.type != "long_silence" else "\u23f8\ufe0f"
            lines.append(f"{icon} **{flag.type.replace('_', ' ').title()}**: {flag.timestamp} - {flag.description}")
            lines.append("")
    else:
        lines.append("---")
        lines.append("")
        lines.append("## Quality Notes")
        lines.append("")
        lines.append("\u2705 **Audio Quality**: No issues detected.")
        lines.append("")

    # --- Footer ---
    lines.append("---")
    lines.append("")
    lines.append(f"_Generated by meeting-notes v0.1.0 on {now.strftime('%Y-%m-%d')} at {now.strftime('%H:%M')}_")

    return "\n".join(lines)


def _render_topics(lines: list[str], extraction: ExtractionResult) -> None:
    if not extraction.topics:
        return
    lines.append("## Key Topics Discussed")
    lines.append("")
    for i, topic in enumerate(extraction.topics, 1):
        title = topic.get("title", "Unknown")
        desc = topic.get("description", "")
        lines.append(f"{i}. **{title}** - {desc}")
    lines.append("")


def _render_decisions(lines: list[str], extraction: ExtractionResult) -> None:
    if not extraction.decisions:
        return
    lines.append("## Decisions Made")
    lines.append("")
    for dec in extraction.decisions:
        text = dec.get("decision", "")
        speaker = dec.get("speaker", "")
        ts = dec.get("timestamp", "")
        lines.append(f"- \u2705 **{text}** ({speaker}, {ts})")
    lines.append("")


def _render_action_items(lines: list[str], extraction: ExtractionResult) -> None:
    if not extraction.action_items:
        return
    lines.append("## Action Items")
    lines.append("")
    for item in extraction.action_items:
        task = item.get("task", "")
        speaker = item.get("speaker", "")
        deadline = item.get("deadline")
        ts = item.get("timestamp", "")
        deadline_str = f", by {deadline}" if deadline else ""
        lines.append(f"- [ ] **{task}** - {speaker}{deadline_str} ({ts})")
    lines.append("")


def _render_questions(lines: list[str], extraction: ExtractionResult) -> None:
    if not extraction.questions:
        return
    lines.append("## Questions & Answers")
    lines.append("")
    for q in extraction.questions:
        question = q.get("question", "")
        asker = q.get("asker", "")
        ts = q.get("timestamp", "")
        answer = q.get("answer")
        answerer = q.get("answerer")
        answer_ts = q.get("answer_timestamp")

        lines.append(f"### \u2753 {question} ({asker}, {ts})")
        lines.append("")
        if answer:
            lines.append(f"**\u2705 Answer**: {answer} ({answerer}, {answer_ts})")
        else:
            lines.append("**\u26a0\ufe0f Unanswered** - This was mentioned but not resolved in the meeting.")
        lines.append("")


def build_sidecar_dict(
    source_file: Path,
    duration: float,
    transcript: TranscriptResult,
    extraction: ExtractionResult | None,
    quality_flags: list[QualityFlag],
    config: Config,
) -> dict:
    """Build a JSON-serializable dict with structured meeting data for database storage."""
    now = datetime.now()
    metadata = {
        "meeting_date": now.strftime("%Y-%m-%d"),
        "meeting_time": now.strftime("%H:%M"),
        "duration": _format_duration(duration),
        "speakers": transcript.speaker_count,
        "audio_file": str(source_file.resolve()),
        "processing_date": now.isoformat(timespec="seconds"),
        "whisper_model": config.whisper_model,
        "llm_model": config.llm_model if extraction else "none",
    }
    if quality_flags:
        metadata["quality_flags"] = [
            {"type": f.type, "timestamp": f.timestamp, "description": f.description}
            for f in quality_flags
        ]

    return {
        "metadata": metadata,
        "summary": {
            "topic_count": len(extraction.topics) if extraction else 0,
            "decision_count": len(extraction.decisions) if extraction else 0,
            "action_item_count": len(extraction.action_items) if extraction else 0,
            "question_count": len(extraction.questions) if extraction else 0,
        },
        "topics": extraction.topics if extraction else [],
        "decisions": extraction.decisions if extraction else [],
        "action_items": extraction.action_items if extraction else [],
        "questions": extraction.questions if extraction else [],
    }


def write_output(
    content: str, source_file: Path, output_dir: Path,
) -> Path:
    """Write Markdown content to output file. Returns the output path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    now = datetime.now()
    filename = f"meeting-{now.strftime('%Y-%m-%d-%H%M%S')}.md"
    output_path = output_dir / filename
    output_path.write_text(content, encoding="utf-8")
    return output_path
